# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
-   repo: https://github.com/asottile/pyupgrade
    rev: v3.3.1
    hooks:
        - id: pyupgrade
-   repo: https://github.com/crate-ci/typos
    rev: v1.13.4
    hooks:
    -   id: typos
-   repo: https://github.com/psf/black
    rev: 22.12.0
    hooks:
        -   id: black
-   repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.11.5
    hooks:
        -   id: ruff
            args:
            - --fix

default_language_version:
    python: python3.12
